# Generated by Django 4.1.3 on 2022-12-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-deadline']},
        ),
    ]
