# Generated by Django 4.1.3 on 2022-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_fee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
