# Generated by Django 4.1.3 on 2022-11-26 09:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appuser_building_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='building_code',
            field=models.IntegerField(default='1166', validators=[core.validators.validate_building_code_length]),
            preserve_default=False,
        ),
    ]
