# Generated by Django 4.1.3 on 2022-11-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_building_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
