# Generated by Django 4.1.3 on 2022-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='admin_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
