# Generated by Django 4.1.3 on 2022-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='apartment_number',
            field=models.CharField(blank=True, default='not specified', max_length=10, null=True),
        ),
    ]
