# Generated by Django 4.1.3 on 2022-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appuser_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='mediafiles/default_profile_pic.webp', null=True, upload_to='images/'),
        ),
    ]
