# Generated by Django 4.1.3 on 2022-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(default='staticfiles/images/blank-profile-picture.png', upload_to='images/'),
        ),
    ]
