# Generated by Django 4.1.3 on 2022-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='apartment_number',
            field=models.CharField(blank=True, default='not specified', max_length=20, null=True),
        ),
    ]
