# Generated by Django 4.1.3 on 2022-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='images/'),
        ),
    ]
