# Generated by Django 4.1.3 on 2022-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmmessages', '0004_chatmessage_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
