# Generated by Django 4.1.3 on 2022-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmmessages', '0005_alter_chatmessage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
