# Generated by Django 4.1.3 on 2022-11-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(blank=True, default='7', on_delete=django.db.models.deletion.RESTRICT, to='home.post'),
            preserve_default=False,
        ),
    ]
